## logging in should return a token
POST http://kubernetes.docker.internal:5000/Admin/User/Authenticate
content-type: application/json
mode: cors

{
    "Password": "asdf",
    "Username": "builder4lyfe",
    "Charity":  "some garbage"
}