### Create team
POST http://kubernetes.docker.internal:5000/Team/Create
Content-Type: application/json
mode: cors

{
    "team":{
        "Name":"run with kyler",
        "Description":"This is bobs team"
    },
    "CharityID": "83af4842-b437-40c7-bb00-fbf22ab1191a"
}

### Update Team
POST http://kubernetes.docker.internal:5000/Team/Create
Content-Type: application/json
mode: cors

{
    "team":{
        "Name":"Bob",
        "Description":"This is bobs team"
    },
    "CharityID": "51a1d9c2-87e4-46da-a42d-65b874628ec9"
}

### GetTeamsByCharityID
GET http://kubernetes.docker.internal:5000/Team/GetByCharityId?CharityId=51a1d9c2-87e4-46da-a42d-65b874628ec9

### Delete Teams
POST http://kubernetes.docker.internal:5000/Team/Delete
Content-Type: application/json
mode: cors

{
    "team":{
        "Name":"Bob",
        "Description":"This is bobs team"
    },
    "CharityID": "51a1d9c2-87e4-46da-a42d-65b874628ec9"
}