POST http://kubernetes.docker.internal:5000/Admin/User/CreateUser
Content-Type: application/json
mode: cors

{
    "FirstName":"Test",
    "LastName":"TheRequest",
    "Username":"Requests4Lyfe",
    "Password":"request",
    "CharityID": "24d2c8e5-d3f2-4144-8925-d25a9e5f505d"
}

###

GET http://kubernetes.docker.internal:5000/Admin/User/GetAll