POST http://kubernetes.docker.internal:5000/Admin/User/CreateUser
Content-Type: application/json
mode: cors

{
    "createUserRequest":{
        "FirstName":"Bob",
        "LastName":"TheBuilder",
        "Username":"Builder4Lyfe",
        "Password":"asdf"
    },
    "charityID": "4b555f96-f477-4245-8b1a-8a4f6aa788a5"
}

###

GET http://kubernetes.docker.internal:5000/Admin/User/GetAll