POST http://kubernetes.docker.internal:5000/Admin/User/CreateUser
Content-Type: application/json
mode: cors

{
    "createUserRequest":{
        "FirstName":"Bob",
        "LastName":"TheBuilder",
        "Username":"Builder4Lyfe",
        "Password":"asdf"
    },
    "CharityID": ""
}