--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2 (Debian 15.2-1.pgdg110+1)
-- Dumped by pg_dump version 15.2 (Debian 15.2-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Donations; Type: TABLE; Schema: public; Owner: aspen
--

CREATE TABLE public."Donations" (
    "ID" bigint NOT NULL,
    "TeamID" bigint,
    "PersonID" bigint,
    "Date" timestamp with time zone NOT NULL,
    "Amount" numeric NOT NULL,
    "IsPledge" boolean DEFAULT false NOT NULL,
    "AuthorizationNumber" text,
    "TransactionNumber" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    "LinkGuid" text
);


ALTER TABLE public."Donations" OWNER TO aspen;

--
-- Name: Donations_ID_seq; Type: SEQUENCE; Schema: public; Owner: aspen
--

ALTER TABLE public."Donations" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Donations_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Events; Type: TABLE; Schema: public; Owner: aspen
--

CREATE TABLE public."Events" (
    "ID" bigint NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Location" text DEFAULT ''::text NOT NULL,
    "Description" text DEFAULT ''::text NOT NULL,
    "Title" text DEFAULT ''::text NOT NULL,
    "DonationTarget" numeric DEFAULT 0.0 NOT NULL,
    "MainImage" text DEFAULT ''::text NOT NULL,
    "IsArchived" boolean DEFAULT false NOT NULL
);


ALTER TABLE public."Events" OWNER TO aspen;

--
-- Name: Events_ID_seq; Type: SEQUENCE; Schema: public; Owner: aspen
--

ALTER TABLE public."Events" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Events_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: LinkRecords; Type: TABLE; Schema: public; Owner: aspen
--

CREATE TABLE public."LinkRecords" (
    "ID" bigint NOT NULL,
    "LinkID" bigint NOT NULL,
    "PersonID" bigint,
    "Date" timestamp with time zone NOT NULL
);


ALTER TABLE public."LinkRecords" OWNER TO aspen;

--
-- Name: LinkRecords_ID_seq; Type: SEQUENCE; Schema: public; Owner: aspen
--

ALTER TABLE public."LinkRecords" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LinkRecords_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Links; Type: TABLE; Schema: public; Owner: aspen
--

CREATE TABLE public."Links" (
    "ID" bigint NOT NULL,
    "EventID" bigint NOT NULL,
    "PersonID" bigint NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "LinkURL" text NOT NULL,
    "LinkGUID" text NOT NULL
);


ALTER TABLE public."Links" OWNER TO aspen;

--
-- Name: Links_ID_seq; Type: SEQUENCE; Schema: public; Owner: aspen
--

ALTER TABLE public."Links" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Links_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PaymentFailures; Type: TABLE; Schema: public; Owner: aspen
--

CREATE TABLE public."PaymentFailures" (
    "ID" bigint NOT NULL,
    "EventID" bigint NOT NULL,
    "PersonID" bigint,
    "Amount" bigint NOT NULL,
    "Code" text NOT NULL,
    "Decline_Code" text,
    "Message" text NOT NULL
);


ALTER TABLE public."PaymentFailures" OWNER TO aspen;

--
-- Name: PaymentFailures_ID_seq; Type: SEQUENCE; Schema: public; Owner: aspen
--

ALTER TABLE public."PaymentFailures" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PaymentFailures_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PersonTeamAssociations; Type: TABLE; Schema: public; Owner: aspen
--

CREATE TABLE public."PersonTeamAssociations" (
    "Id" integer NOT NULL,
    "PersonId" bigint NOT NULL,
    "TeamId" bigint NOT NULL,
    "EventId" bigint NOT NULL,
    "DateJoined" timestamp with time zone NOT NULL
);


ALTER TABLE public."PersonTeamAssociations" OWNER TO aspen;

--
-- Name: PersonTeamAssociations_Id_seq; Type: SEQUENCE; Schema: public; Owner: aspen
--

ALTER TABLE public."PersonTeamAssociations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PersonTeamAssociations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Persons; Type: TABLE; Schema: public; Owner: aspen
--

CREATE TABLE public."Persons" (
    "ID" bigint NOT NULL,
    "AuthID" text DEFAULT ''::text NOT NULL,
    "Name" text DEFAULT ''::text NOT NULL,
    "Bio" text,
    "Nickname" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Persons" OWNER TO aspen;

--
-- Name: Persons_ID_seq; Type: SEQUENCE; Schema: public; Owner: aspen
--

ALTER TABLE public."Persons" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Persons_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Teams; Type: TABLE; Schema: public; Owner: aspen
--

CREATE TABLE public."Teams" (
    "ID" bigint NOT NULL,
    "Description" text DEFAULT ''::text NOT NULL,
    "MainImage" text DEFAULT ''::text NOT NULL,
    "OwnerID" bigint NOT NULL,
    "EventID" bigint NOT NULL,
    "Name" character varying(128) DEFAULT ''::character varying NOT NULL,
    "DonationTarget" numeric DEFAULT 0.0 NOT NULL,
    "IsArchived" boolean DEFAULT false NOT NULL,
    "WelcomeMessage" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Teams" OWNER TO aspen;

--
-- Name: Teams_ID_seq; Type: SEQUENCE; Schema: public; Owner: aspen
--

ALTER TABLE public."Teams" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Teams_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: aspen
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO aspen;

--
-- Data for Name: Donations; Type: TABLE DATA; Schema: public; Owner: aspen
--

COPY public."Donations" ("ID", "TeamID", "PersonID", "Date", "Amount", "IsPledge", "AuthorizationNumber", "TransactionNumber", "LinkGuid") FROM stdin;
\.


--
-- Data for Name: Events; Type: TABLE DATA; Schema: public; Owner: aspen
--

COPY public."Events" ("ID", "Date", "Location", "Description", "Title", "DonationTarget", "MainImage", "IsArchived") FROM stdin;
1	2024-09-21 21:27:34.959+00	Somewhere	Event	Awesome Event	2500000	image	f
\.


--
-- Data for Name: LinkRecords; Type: TABLE DATA; Schema: public; Owner: aspen
--

COPY public."LinkRecords" ("ID", "LinkID", "PersonID", "Date") FROM stdin;
\.


--
-- Data for Name: Links; Type: TABLE DATA; Schema: public; Owner: aspen
--

COPY public."Links" ("ID", "EventID", "PersonID", "Date", "LinkURL", "LinkGUID") FROM stdin;
\.


--
-- Data for Name: PaymentFailures; Type: TABLE DATA; Schema: public; Owner: aspen
--

COPY public."PaymentFailures" ("ID", "EventID", "PersonID", "Amount", "Code", "Decline_Code", "Message") FROM stdin;
\.


--
-- Data for Name: PersonTeamAssociations; Type: TABLE DATA; Schema: public; Owner: aspen
--

COPY public."PersonTeamAssociations" ("Id", "PersonId", "TeamId", "EventId", "DateJoined") FROM stdin;
\.


--
-- Data for Name: Persons; Type: TABLE DATA; Schema: public; Owner: aspen
--

COPY public."Persons" ("ID", "AuthID", "Name", "Bio", "Nickname") FROM stdin;
1	1	anthony	im awesome	anthony
\.


--
-- Data for Name: Teams; Type: TABLE DATA; Schema: public; Owner: aspen
--

COPY public."Teams" ("ID", "Description", "MainImage", "OwnerID", "EventID", "Name", "DonationTarget", "IsArchived", "WelcomeMessage") FROM stdin;
1	Awesome Team	image	1	1	Awesome Team	250000000	f	Welcome to Awesome
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: aspen
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20211021045038_recordDbModels	7.0.2
20211028151658_MakePageDataKeyUnique	7.0.2
20211106022222_AddedEventTitle	7.0.2
20211116051848_AddNameColumnToTeam	7.0.2
20211122213424_AddDonationTable	7.0.2
20211123150738_RenamePendingColumn	7.0.2
20211123152418_AddDonationTargetToEvent	7.0.2
20211203211130_AddDonationTargetToTeam	7.0.2
20221104222427_MigrateToEF6	7.0.2
20221107042731_IsPledge	7.0.2
20221115171355_PublicPrivateTeam	7.0.2
20221201024052_Added New DataModel to the Team	7.0.2
20230119184323_ChangeDonationModel	7.0.2
20230131150739_AddedLinkTables	7.0.2
20230206195820_addedUpdateToDonationTable	7.0.2
20230208202242_failurePaymentTable	7.0.2
20230208231153_nullableDeclineCode	7.0.2
20230215011546_UpdateLinkTable	7.0.2
20230215194255_RemovedOageData	7.0.2
20230215232136_RemovedEventId	7.0.2
20230217204015_nicknametopersontable	7.0.2
20230222003518_PersonTeamAssociationsTable	7.0.2
20230223003336_CreatedArchivedColumn	7.0.2
20230319193247_welcomeMessageInTeamTable	7.0.2
\.


--
-- Name: Donations_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: aspen
--

SELECT pg_catalog.setval('public."Donations_ID_seq"', 1, false);


--
-- Name: Events_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: aspen
--

SELECT pg_catalog.setval('public."Events_ID_seq"', 1, true);


--
-- Name: LinkRecords_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: aspen
--

SELECT pg_catalog.setval('public."LinkRecords_ID_seq"', 1, false);


--
-- Name: Links_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: aspen
--

SELECT pg_catalog.setval('public."Links_ID_seq"', 1, false);


--
-- Name: PaymentFailures_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: aspen
--

SELECT pg_catalog.setval('public."PaymentFailures_ID_seq"', 1, false);


--
-- Name: PersonTeamAssociations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: aspen
--

SELECT pg_catalog.setval('public."PersonTeamAssociations_Id_seq"', 1, false);


--
-- Name: Persons_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: aspen
--

SELECT pg_catalog.setval('public."Persons_ID_seq"', 1, false);


--
-- Name: Teams_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: aspen
--

SELECT pg_catalog.setval('public."Teams_ID_seq"', 1, true);


--
-- Name: Donations PK_Donations; Type: CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."Donations"
    ADD CONSTRAINT "PK_Donations" PRIMARY KEY ("ID");


--
-- Name: Events PK_Events; Type: CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."Events"
    ADD CONSTRAINT "PK_Events" PRIMARY KEY ("ID");


--
-- Name: LinkRecords PK_LinkRecords; Type: CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."LinkRecords"
    ADD CONSTRAINT "PK_LinkRecords" PRIMARY KEY ("ID");


--
-- Name: Links PK_Links; Type: CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."Links"
    ADD CONSTRAINT "PK_Links" PRIMARY KEY ("ID");


--
-- Name: PaymentFailures PK_PaymentFailures; Type: CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."PaymentFailures"
    ADD CONSTRAINT "PK_PaymentFailures" PRIMARY KEY ("ID");


--
-- Name: PersonTeamAssociations PK_PersonTeamAssociations; Type: CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."PersonTeamAssociations"
    ADD CONSTRAINT "PK_PersonTeamAssociations" PRIMARY KEY ("Id");


--
-- Name: Persons PK_Persons; Type: CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."Persons"
    ADD CONSTRAINT "PK_Persons" PRIMARY KEY ("ID");


--
-- Name: Teams PK_Teams; Type: CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."Teams"
    ADD CONSTRAINT "PK_Teams" PRIMARY KEY ("ID");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Donations_PersonID; Type: INDEX; Schema: public; Owner: aspen
--

CREATE INDEX "IX_Donations_PersonID" ON public."Donations" USING btree ("PersonID");


--
-- Name: IX_Donations_TeamID; Type: INDEX; Schema: public; Owner: aspen
--

CREATE INDEX "IX_Donations_TeamID" ON public."Donations" USING btree ("TeamID");


--
-- Name: IX_LinkRecords_LinkID; Type: INDEX; Schema: public; Owner: aspen
--

CREATE INDEX "IX_LinkRecords_LinkID" ON public."LinkRecords" USING btree ("LinkID");


--
-- Name: IX_Links_EventID; Type: INDEX; Schema: public; Owner: aspen
--

CREATE INDEX "IX_Links_EventID" ON public."Links" USING btree ("EventID");


--
-- Name: IX_Links_PersonID; Type: INDEX; Schema: public; Owner: aspen
--

CREATE INDEX "IX_Links_PersonID" ON public."Links" USING btree ("PersonID");


--
-- Name: IX_PaymentFailures_EventID; Type: INDEX; Schema: public; Owner: aspen
--

CREATE INDEX "IX_PaymentFailures_EventID" ON public."PaymentFailures" USING btree ("EventID");


--
-- Name: IX_PaymentFailures_PersonID; Type: INDEX; Schema: public; Owner: aspen
--

CREATE INDEX "IX_PaymentFailures_PersonID" ON public."PaymentFailures" USING btree ("PersonID");


--
-- Name: IX_PersonTeamAssociations_EventId; Type: INDEX; Schema: public; Owner: aspen
--

CREATE INDEX "IX_PersonTeamAssociations_EventId" ON public."PersonTeamAssociations" USING btree ("EventId");


--
-- Name: IX_PersonTeamAssociations_PersonId_EventId; Type: INDEX; Schema: public; Owner: aspen
--

CREATE UNIQUE INDEX "IX_PersonTeamAssociations_PersonId_EventId" ON public."PersonTeamAssociations" USING btree ("PersonId", "EventId");


--
-- Name: IX_PersonTeamAssociations_TeamId; Type: INDEX; Schema: public; Owner: aspen
--

CREATE INDEX "IX_PersonTeamAssociations_TeamId" ON public."PersonTeamAssociations" USING btree ("TeamId");


--
-- Name: IX_Teams_EventID; Type: INDEX; Schema: public; Owner: aspen
--

CREATE INDEX "IX_Teams_EventID" ON public."Teams" USING btree ("EventID");


--
-- Name: IX_Teams_OwnerID; Type: INDEX; Schema: public; Owner: aspen
--

CREATE INDEX "IX_Teams_OwnerID" ON public."Teams" USING btree ("OwnerID");


--
-- Name: Donations FK_Donations_Persons_PersonID; Type: FK CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."Donations"
    ADD CONSTRAINT "FK_Donations_Persons_PersonID" FOREIGN KEY ("PersonID") REFERENCES public."Persons"("ID") ON DELETE RESTRICT;


--
-- Name: Donations FK_Donations_Teams_TeamID; Type: FK CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."Donations"
    ADD CONSTRAINT "FK_Donations_Teams_TeamID" FOREIGN KEY ("TeamID") REFERENCES public."Teams"("ID") ON DELETE RESTRICT;


--
-- Name: LinkRecords FK_LinkRecords_Links_LinkID; Type: FK CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."LinkRecords"
    ADD CONSTRAINT "FK_LinkRecords_Links_LinkID" FOREIGN KEY ("LinkID") REFERENCES public."Links"("ID") ON DELETE CASCADE;


--
-- Name: Links FK_Links_Events_EventID; Type: FK CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."Links"
    ADD CONSTRAINT "FK_Links_Events_EventID" FOREIGN KEY ("EventID") REFERENCES public."Events"("ID") ON DELETE CASCADE;


--
-- Name: Links FK_Links_Persons_PersonID; Type: FK CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."Links"
    ADD CONSTRAINT "FK_Links_Persons_PersonID" FOREIGN KEY ("PersonID") REFERENCES public."Persons"("ID") ON DELETE CASCADE;


--
-- Name: PaymentFailures FK_PaymentFailures_Events_EventID; Type: FK CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."PaymentFailures"
    ADD CONSTRAINT "FK_PaymentFailures_Events_EventID" FOREIGN KEY ("EventID") REFERENCES public."Events"("ID") ON DELETE CASCADE;


--
-- Name: PaymentFailures FK_PaymentFailures_Persons_PersonID; Type: FK CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."PaymentFailures"
    ADD CONSTRAINT "FK_PaymentFailures_Persons_PersonID" FOREIGN KEY ("PersonID") REFERENCES public."Persons"("ID");


--
-- Name: PersonTeamAssociations FK_PersonTeamAssociations_Events_EventId; Type: FK CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."PersonTeamAssociations"
    ADD CONSTRAINT "FK_PersonTeamAssociations_Events_EventId" FOREIGN KEY ("EventId") REFERENCES public."Events"("ID") ON DELETE CASCADE;


--
-- Name: PersonTeamAssociations FK_PersonTeamAssociations_Persons_PersonId; Type: FK CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."PersonTeamAssociations"
    ADD CONSTRAINT "FK_PersonTeamAssociations_Persons_PersonId" FOREIGN KEY ("PersonId") REFERENCES public."Persons"("ID") ON DELETE CASCADE;


--
-- Name: PersonTeamAssociations FK_PersonTeamAssociations_Teams_TeamId; Type: FK CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."PersonTeamAssociations"
    ADD CONSTRAINT "FK_PersonTeamAssociations_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES public."Teams"("ID") ON DELETE CASCADE;


--
-- Name: Teams FK_Teams_Events_EventID; Type: FK CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."Teams"
    ADD CONSTRAINT "FK_Teams_Events_EventID" FOREIGN KEY ("EventID") REFERENCES public."Events"("ID") ON DELETE CASCADE;


--
-- Name: Teams FK_Teams_Persons_OwnerID; Type: FK CONSTRAINT; Schema: public; Owner: aspen
--

ALTER TABLE ONLY public."Teams"
    ADD CONSTRAINT "FK_Teams_Persons_OwnerID" FOREIGN KEY ("OwnerID") REFERENCES public."Persons"("ID") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

