# base image
FROM node:12.2.0-alpine
# set working directory
WORKDIR /ClientApp
# The base node image sets a very verbose log level.
ENV NPM_CONFIG_LOGLEVEL warn
# Copy all local files into the image.
COPY . .
# Build for production.
RUN npm install
RUN npm start
# Tell Docker about the port we'll run on.
EXPOSE 3000