name: Push to Docker Hub
on:
  push:
    tags:
      - 'v*.*'
  workflow_dispatch:
    
jobs:
  run-tests:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.4.0

      
      - name: build and test
        run: |
          # cd ops/testing
          # DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build --parallel --pull
          # docker-compose up -d
          # docker-compose exec -T api_test dotnet test api-tests
          # docker-compose exec -T web_test npm run test
          # docker-compose exec -T web_test npm run lint -- --max-warnings 0
          # docker-compose down

  build-api:    
    runs-on: [ubuntu-latest]
    needs: [run-tests]
    env:
      IMAGE_NAME: snowcollege/aspen_api
      DOCKERFILE: src/combined/Dockerfile
      DOCKER_BUILDKIT: 1 
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build container
        working-directory: src
        run: docker build -t ${{ env.IMAGE_NAME }} -f ${{ env.DOCKERFILE }} .

      - name: push container
        run: docker push ${{ env.IMAGE_NAME }} 

  build-keycloak:    
    runs-on: [ubuntu-latest]
    needs: [run-tests]
    env:
      IMAGE_NAME: snowcollege/aspen_keycloak
      DOCKERFILE: dev-resources/keycloak/Dockerfile
      DOCKER_BUILDKIT: 1 
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build container
        working-directory: dev-resources/keycloak
        run: docker build -t ${{ env.IMAGE_NAME }} -f ${{ env.DOCKERFILE }} .

      - name: push container
        run: docker push ${{ env.IMAGE_NAME }}     

  build-reverseproxy:    
    runs-on: [ubuntu-latest]
    needs: [run-tests]
    env:
      IMAGE_NAME: snowcollege/aspen_reverseproxy
      DOCKERFILE: ops/staging/reverse-proxy/Dockerfile
      DOCKER_BUILDKIT: 1 
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build container
        run: docker build -t ${{ env.IMAGE_NAME }} -f ${{ env.DOCKERFILE }} .

      - name: push container
        run: docker push ${{ env.IMAGE_NAME }}          
